# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b887080db9f562596abce9790a89d93bbd92e2174b4e6fc9029439bf475cde04d5b6e50513eef45e8b0e3e0a1e221d643988b59afcdc009e078cba496ceb751

test:
  secret_key_base: ebbb1a117a02305d644bf8ca55d316fe8be166774bcfef308a4d17cddfc8e20000c6abe1de7d2eed436298fc667b6c33e0da4927d4698894cfd01bad5335f1ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
